server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: recuperar-senha-service
          uri: http://recuperar-senha-service:8085
          predicates:
            - Path=/password-recovery/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: login-auth-api
          uri: http://login-auth-api:8081
          predicates:
            - Path=/auth/**,/user/**

        - id: gastos-services
          uri: http://gastos-services:8082
          predicates:
            - Path=/gastos/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: gastos-service-parcelas
          uri: http://gastos-service-parcelas:8082
          predicates:
            - Path=/parcelas/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: categorias-services
          uri: http://categorias-services:8083
          predicates:
            - Path=/categorias/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: investimentos-service
          uri: http://localhost:8084
          predicates:
            - Path=/investimentos/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: investimentos-service-compras
          uri: http://localhost:8084
          predicates:
            - Path=/compras/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: investimentos-service-rendas
          uri: http://localhost:8084
          predicates:
            - Path=/rendas/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: divisao-service
          uri: http://divisao-service:8086
          predicates:
            - Path=/divisao/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: relatorios-service
          uri: http://relatorios-service:8087
          predicates:
            - Path=/relatorios/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

      default-filters:
        - AddResponseHeader=X-Gateway, ControleGastosAPI

  main:
    web-application-type: reactive