server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: gastos-service-gastos
          uri: http://localhost:8082
          predicates:
            - Path=/gastos/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: gastos-service-parcelas
          uri: http://localhost:8082
          predicates:
            - Path=/parcelas/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: categorias-service
          uri: http://localhost:8083
          predicates:
            - Path=/categorias/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

        - id: investimentos-service
          uri: http://localhost:8084
          predicates:
            - Path=/investimentos/**
          filters:
            - PreserveHostHeader
            - RemoveRequestHeader=Cookie

      default-filters:
        - AddResponseHeader=X-Gateway, ControleGastosAPI

  main:
    web-application-type: reactive